[project]
name = "pdf-ruiner"
version = "0.1.0"
description = "ruins your pdf files in a terrible way"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.0",
    "pikepdf>=10.0.3",
    "pymupdf>=1.26.7",
]
